In [127]:
import pandas as pd
import numpy as np

In [128]:
!pip install openpyxl

In [129]:
data = pd.read_excel("bio-degradabale-data.xlsx", header=None)
data.head()

0       1   2   3   4   5   6     7   8   9   ...  32  33  34     35  \
0  3.919  2.6909   0   0   0   0   0  31.4   2   0  ...   0   0   0  2.949   
1  4.170  2.1144   0   0   0   0   0  30.8   1   1  ...   0   0   0  3.315   
2  3.932  3.2512   0   0   0   0   0  26.7   2   4  ...   0   0   1  3.076   
3  3.000  2.7098   0   0   0   0   0  20.0   0   2  ...   0   0   1  3.046   
4  4.236  3.3944   0   0   0   0   0  29.4   2   4  ...   0   0   0  3.351   

      36  37     38  39  40  41  
0  1.591   0  7.253   0   0  RB  
1  1.967   0  7.257   0   0  RB  
2  2.417   0  7.601   0   0  RB  
3  5.000   0  6.690   0   0  RB  
4  2.405   0  8.003   0   0  RB  

[5 rows x 42 columns]

In [130]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 42 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       1055 non-null   float64
 1   1       1055 non-null   float64
 2   2       1055 non-null   int64  
 3   3       1055 non-null   int64  
 4   4       1055 non-null   int64  
 5   5       1055 non-null   int64  
 6   6       1055 non-null   int64  
 7   7       1055 non-null   float64
 8   8       1055 non-null   int64  
 9   9       1055 non-null   int64  
 10  10      1055 non-null   int64  
 11  11      1055 non-null   float64
 12  12      1055 non-null   float64
 13  13      1055 non-null   float64
 14  14      1055 non-null   float64
 15  15      1055 non-null   int64  
 16  16      1055 non-null   float64
 17  17      1055 non-null   float64
 18  18      1055 non-null   int64  
 19  19      1055 non-null   int64  
 20  20      1055 non-null   int64  
 21  21      1055 non-null   float64
 22  

In [131]:
data.isna()

0      1      2      3      4      5      6      7      8      9   \
0     False  False  False  False  False  False  False  False  False  False   
1     False  False  False  False  False  False  False  False  False  False   
2     False  False  False  False  False  False  False  False  False  False   
3     False  False  False  False  False  False  False  False  False  False   
4     False  False  False  False  False  False  False  False  False  False   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1050  False  False  False  False  False  False  False  False  False  False   
1051  False  False  False  False  False  False  False  False  False  False   
1052  False  False  False  False  False  False  False  False  False  False   
1053  False  False  False  False  False  False  False  False  False  False   
1054  False  False  False  False  False  False  False  False  False  False   

      ...     32     33     34     35     36     37     38     39     40  \
0     ...  False  False  False  False  False  False  False  False  False   
1     ...  False  False  False  False  False  False  False  False  False   
2     ...  False  False  False  False  False  False  False  False  False   
3     ...  False  False  False  False  False  False  False  False  False   
4     ...  False  False  False  False  False  False  False  False  False   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1050  ...  False  False  False  False  False  False  False  False  False   
1051  ...  False  False  False  False  False  False  False  False  False   
1052  ...  False  False  False  False  False  False  False  False  False   
1053  ...  False  False  False  False  False  False  False  False  False   
1054  ...  False  False  False  False  False  False  False  False  False   

         41  
0     False  
1     False  
2     False  
3     False  
4     False  
...     ...  
1050  False  
1051  False  
1052  False  
1053  False  
1054  False  

[1055 rows x 42 columns]

In [132]:
print(data.isnull().sum())

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
dtype: int64


In [133]:
X=data.iloc[:,0:41]
Y=data.iloc[:,41:42]
Y

41
0      RB
1      RB
2      RB
3      RB
4      RB
...   ...
1050  NRB
1051  NRB
1052  NRB
1053  NRB
1054  NRB

[1055 rows x 1 columns]

In [134]:
from sklearn.preprocessing import LabelEncoder

In [135]:
le=LabelEncoder()
y=le.fit_transform(Y)
le.inverse_transform([0,1])
y

c:\users\tejshree reddy\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([1, 1, 1, ..., 0, 0, 0])

In [136]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,train_size=0.25,random_state=1)

In [137]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [138]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR=LR.fit(x_train,y_train)
y_pred_LR=LR.predict(x_test)

In [139]:
accuracy_score(y_test,y_pred_LR)

0.8409090909090909

In [141]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred_LR)


array([[470,  50],
       [ 76, 196]], dtype=int64)

In [140]:
from sklearn.tree import DecisionTreeClassifier
DTC = DecisionTreeClassifier(random_state = 0)
DTC=DTC.fit(x_train, y_train)
y_pred_DTC=DTC.predict(x_test)

In [126]:
accuracy_score(y_test, y_pred_DTC)

0.7840909090909091

In [142]:
confusion_matrix(y_test, y_pred_DTC)


array([[450,  70],
       [101, 171]], dtype=int64)

In [143]:

from sklearn.svm import SVC
SVC= SVC()
SVC=SVC.fit(x_train, y_train)
y_pred_SVC = SVC.predict(x_test)
accuracy_score(y_test, y_pred_SVC)

0.8497474747474747

In [144]:
confusion_matrix(y_test, y_pred_SVC)


array([[483,  37],
       [ 82, 190]], dtype=int64)

In [145]:
from sklearn.neighbors import KNeighborsClassifier
KNN= KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
KNN=KNN.fit(x_train, y_train)
y_pred_KNN = KNN.predict(x_test)
accuracy_score(y_test, y_pred_KNN)

0.821969696969697

In [147]:
confusion_matrix(y_test, y_pred_KNN)


array([[443,  77],
       [ 64, 208]], dtype=int64)

In [152]:
from sklearn.naive_bayes import GaussianNB
NB = GaussianNB()
NB=NB.fit(x_train, y_train)
y_pred_NB =NB.predict(x_test)
accuracy_score(y_test, y_pred_NB)



0.6553030303030303

In [153]:
confusion_matrix(y_test, y_pred_NB)


array([[269, 251],
       [ 22, 250]], dtype=int64)

In [160]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators = 20, criterion = 'entropy', random_state = 51)
RF=RF.fit(x_train, y_train)
y_pred_RF = RF.predict(x_test)
accuracy_score(y_test, y_pred_RF)

0.8383838383838383

In [161]:
confusion_matrix(y_test, y_pred_RF)


array([[491,  29],
       [ 99, 173]], dtype=int64)

In [162]:
!pip install xgboost

In [163]:
from xgboost import XGBClassifier
XGB = XGBClassifier()
XGB=XGB.fit(x_train, y_train)
y_pred_XGB = XGB.predict(x_test)
accuracy_score(y_test, y_pred_XGB)

[20:41:25] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


c:\users\tejshree reddy\appdata\local\programs\python\python39\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


0.8472222222222222

In [164]:
confusion_matrix(y_test, y_pred_XGB)


array([[477,  43],
       [ 78, 194]], dtype=int64)