In [232]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [233]:
CD=pd.read_csv("breast-cancer-data.csv")

In [234]:
CD.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [235]:
CD.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [281]:
CD.isnull().any()

id                         False
diagnosis                  False
radius_mean                False
texture_mean               False
perimeter_mean             False
area_mean                  False
smoothness_mean            False
compactness_mean           False
concavity_mean             False
concave points_mean        False
symmetry_mean              False
fractal_dimension_mean     False
radius_se                  False
texture_se                 False
perimeter_se               False
area_se                    False
smoothness_se              False
compactness_se             False
concavity_se               False
concave points_se          False
symmetry_se                False
fractal_dimension_se       False
radius_worst               False
texture_worst              False
perimeter_worst            False
area_worst                 False
smoothness_worst           False
compactness_worst          False
concavity_worst            False
concave points_worst       False
symmetry_w

In [282]:
cancer_data=CD.drop(["id"],axis=1)
dataY=cancer_data["diagnosis"]

In [283]:
dataX=cancer_data.drop(["diagnosis"],axis=1)

In [284]:
dataY=cancer_data["diagnosis"]

In [285]:
from sklearn.preprocessing import LabelEncoder

In [286]:
le=LabelEncoder()

In [243]:
df=le.fit_transform(dataY)

In [244]:
dataY1=pd.DataFrame(df)

In [245]:
from sklearn.decomposition import PCA

In [246]:
pc=PCA()

In [247]:
pca_before=pc.fit(dataX)

In [248]:
datax=pd.DataFrame(pc.transform(dataX))

In [249]:
pca_before.explained_variance_

array([4.43782605e+05, 7.31010006e+03, 7.03833742e+02, 5.46487379e+01,
       3.98900178e+01, 3.00458768e+00, 1.81533030e+00, 3.71466740e-01,
       1.55513547e-01, 8.40612196e-02, 3.16089533e-02, 7.49736514e-03,
       3.16165652e-03, 2.16150395e-03, 1.32653879e-03, 6.40269304e-04,
       3.74883320e-04, 2.35169626e-04, 1.84583467e-04, 1.64180064e-04,
       7.81102011e-05, 5.76111660e-05, 3.49172775e-05, 2.83952689e-05,
       1.61463677e-05, 1.24902419e-05, 3.68048171e-06, 2.84790425e-06,
       2.00491564e-06, 7.01997261e-07])

In [250]:
pca_before.explained_variance_ratio_

array([9.82044672e-01, 1.61764899e-02, 1.55751075e-03, 1.20931964e-04,
       8.82724536e-05, 6.64883951e-06, 4.01713682e-06, 8.22017197e-07,
       3.44135279e-07, 1.86018721e-07, 6.99473205e-08, 1.65908880e-08,
       6.99641650e-09, 4.78318306e-09, 2.93549214e-09, 1.41684927e-09,
       8.29577731e-10, 5.20405883e-10, 4.08463983e-10, 3.63313378e-10,
       1.72849737e-10, 1.27487508e-10, 7.72682973e-11, 6.28357718e-11,
       3.57302295e-11, 2.76396041e-11, 8.14452259e-12, 6.30211541e-12,
       4.43666945e-12, 1.55344680e-12])

In [251]:
pca_before.singular_values_

array([1.58766659e+04, 2.03767928e+03, 6.32279658e+02, 1.76183095e+02,
       1.50524184e+02, 4.13110857e+01, 3.21108643e+01, 1.45256018e+01,
       9.39849429e+00, 6.90990396e+00, 4.23720255e+00, 2.06361416e+00,
       1.34008242e+00, 1.10803170e+00, 8.68028820e-01, 6.03053036e-01,
       4.61447425e-01, 3.65480981e-01, 3.23795320e-01, 3.05375632e-01,
       2.10633792e-01, 1.80895390e-01, 1.40829733e-01, 1.26998082e-01,
       9.57660526e-02, 8.42286020e-02, 4.57221348e-02, 4.02195178e-02,
       3.37459936e-02, 1.99683360e-02])

In [252]:
from sklearn.model_selection import train_test_split

In [253]:
trainx,testx,trainy,testy=train_test_split(datax,dataY1,test_size=0.3)

In [254]:
from sklearn.linear_model import LogisticRegression


In [255]:
lr=LogisticRegression()

In [256]:
lr.fit(trainx,trainy)

c:\users\welcome\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\welcome\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [257]:
pca_pred=lr.predict(testx)

In [258]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [259]:
accuracy_score(testy,pca_pred)

0.9473684210526315

In [260]:
pc1=PCA(5)

In [261]:
pca_after=pc1.fit(dataX)

In [262]:
pca_after.explained_variance_

array([4.43782605e+05, 7.31010006e+03, 7.03833742e+02, 5.46487379e+01,
       3.98900178e+01])

In [263]:
pca_after.explained_variance_ratio_

array([9.82044672e-01, 1.61764899e-02, 1.55751075e-03, 1.20931964e-04,
       8.82724536e-05])

In [264]:
datax1=pd.DataFrame(pc1.transform(dataX))

In [265]:
trainx,testx,trainy,testy=train_test_split(datax1,dataY1,test_size=0.2)

In [266]:
lr.fit(trainx,trainy)

c:\users\welcome\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [267]:
pca1_pred=lr.predict(testx)

In [268]:
accuracy_score(testy,pca1_pred)

0.9210526315789473

In [269]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [270]:
trainx,testx,trainy,testy=train_test_split(dataX,dataY1,test_size=0.2)

In [271]:
ld=LDA()

In [272]:
ld.fit(trainx,trainy)

c:\users\welcome\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
                           solver='svd', store_covariance=False, tol=0.0001)

In [273]:
lda_pred=ld.predict(testx)

In [274]:
accuracy_score(testy,lda_pred)

0.9736842105263158